language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - blead
matrix:
  allow_failures:
    - perl: blead
services:
  - rabbitmq
env:
  - "HARNESS_OPTIONS=j9 TEST_POD=1"
install:
  - "cpanm -n Module::Install Module::Install::AuthorTests Test::Pod"
  - "cpanm -n --installdeps ."
